### ISSUE TITLE
Which file to put into UnityLive2DExtractor

### ISSUE THREAD

**Issue by jiaoxiaohang** [SerenityS/memo_live2d#1]
Hello
I want to extract the l2d of the character myself, but I don’t know which file to put into UnityLive2DExtractor after unpacking it. Can you explain the extraction process in detail?
grateful
<img width="143" alt="image" src="https://github.com/SerenityS/memo_live2d/assets/69664925/4f8bf75b-59be-4a52-963a-9de25d4a57a5">

**Comment by jiaoxiaohang** [comment]
I put the source file into UnityLive2DExtractor and successfully extracted the moc3 file, but the motion file is an empty file. How do I extract the action file?
![image](https://github.com/SerenityS/memo_live2d/assets/69664925/1be70774-3c6b-4e44-a4de-b67f7e8387ce)

**Comment by jiaoxiaohang** [comment]
I learned that AssetStudio cannot export AnimationClip separately. How did you export it?

**Comment by SerenityS** [comment]
Hello.

It's been a long time since I worked on it, so I can't remember which file to export.

In the case of MementoMori, UnityLive2DExtractor needs to be modified.
Check this [UnityLive2DExtractor](https://github.com/SerenityS/UnityLive2DExtractor)

I remember that I had to extract each character because it was temporarily fixed.

**Comment by jiaoxiaohang** [comment]
Thank you for your reply. Recently, I found the modified UnityLive2DExtractor and it is now ready to export the motion file
